# Generated by Django 3.1.7 on 2021-02-24 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('byline', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=350)),
                ('time_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('author_of_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug_tracker.author')),
            ],
        ),
    ]
