# Generated by Django 3.1.7 on 2021-02-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug_tracker', '0003_auto_20210226_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignee_of_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_of_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closer_of_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closer_of_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status_of_ticket',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=24),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author_of_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
