# Generated by Django 3.1.7 on 2021-02-26 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug_tracker', '0004_auto_20210226_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='author_of_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_of_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
